// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import FavoriteHeartController from "./favorite_heart_controller"
application.register("favorite-heart", FavoriteHeartController)

import HeartsController from "./hearts_controller"
application.register("hearts", HeartsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import OpenreviewformController from "./openreviewform_controller"
application.register("openreviewform", OpenreviewformController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
